//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGCalificaciones.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materia_Curso
    {
        public int id_asignacion { get; set; }
        public Nullable<int> id_curso { get; set; }
        public Nullable<int> id_materia { get; set; }
    
        public virtual Curso Curso { get; set; }
        public virtual Materia Materia { get; set; }
    }
}
